version: '3.1'

services:
  app:
    container_name: iclock-emqx-mongo-connector
    build: .
    env_file:
      - stack.env
    networks:
      - emqxNet

networks:
  emqxNet:
    name: emqxNet
    external: true