version: '3.1'

services:
  app:
    container_name: nodejs-app
    build: .
    ports:
      - "5123:5123"
    env_file:
      - stack.env
    networks:
      - emqxNet

networks:
  emqxNet:
    name: emqxNet
    external: true